services:
  nginx:
    build:
      context: .
    image: nginx-local        
    ports:
      - "80:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./public:/usr/share/nginx/html/public
    restart: always
